# Generated by Django 4.1 on 2022-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=240, verbose_name='Name')),
                ('petrol', models.CharField(max_length=240, verbose_name='Petrol')),
                ('diesel', models.CharField(max_length=240, verbose_name='Diesel')),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
