# Generated by Django 4.1 on 2022-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blugold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='google_id',
            field=models.CharField(default=0, max_length=240, verbose_name='google_id'),
            preserve_default=False,
        ),
    ]
